package PackageManager;


/**
* PackageManager/ManagerClientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLmanager.idl
* Saturday, July 8, 2017 1:27:51 o'clock PM EDT
*/

abstract public class ManagerClientHelper
{
  private static String  _id = "IDL:PackageManager/ManagerClient:1.0";

  public static void insert (org.omg.CORBA.Any a, PackageManager.ManagerClient that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PackageManager.ManagerClient extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PackageManager.ManagerClientHelper.id (), "ManagerClient");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PackageManager.ManagerClient read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ManagerClientStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PackageManager.ManagerClient value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PackageManager.ManagerClient narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PackageManager.ManagerClient)
      return (PackageManager.ManagerClient)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PackageManager._ManagerClientStub stub = new PackageManager._ManagerClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PackageManager.ManagerClient unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PackageManager.ManagerClient)
      return (PackageManager.ManagerClient)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PackageManager._ManagerClientStub stub = new PackageManager._ManagerClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
