package PackageManager;

/**
* PackageManager/ManagerClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLmanager.idl
* Saturday, July 8, 2017 1:27:51 o'clock PM EDT
*/

public final class ManagerClientHolder implements org.omg.CORBA.portable.Streamable
{
  public PackageManager.ManagerClient value = null;

  public ManagerClientHolder ()
  {
  }

  public ManagerClientHolder (PackageManager.ManagerClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PackageManager.ManagerClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PackageManager.ManagerClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PackageManager.ManagerClientHelper.type ();
  }

}
