package PackageManager;


/**
* PackageManager/ManagerClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLmanager.idl
* Saturday, July 8, 2017 1:27:51 o'clock PM EDT
*/

public interface ManagerClient extends ManagerClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ManagerClient
