package PackageManager;


/**
* PackageManager/ManagerClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLmanager.idl
* Saturday, July 8, 2017 1:27:51 o'clock PM EDT
*/

public interface ManagerClientOperations 
{
  String createTRecord (String fname, String lname, String address, String phone, String speical, String location, String manID);
  String createSRecord (String fname, String lname, String crsReg, String status, String statusDate, String manID);
  String getRecordCounts (String manID);
  String editRecord (String recID, String fieldName, String newValue, String manID);
  String displayAllRecords (String manID);
  String displayRecord (String manID, String recID);
  String transferRecord (String recID, String toServer, String manID);
  void shutdown ();
} // interface ManagerClientOperations
